"""empty message

Revision ID: 11239c27e62a
Revises: 9af43862368f
Create Date: 2017-08-22 12:17:00.793566

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '11239c27e62a'
down_revision = '9af43862368f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('github_web_hook',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('repository_link_id', sa.Integer(), nullable=True),
    sa.Column('hook_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['repository_link_id'], ['repository_link.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('github_web_hook')
    # ### end Alembic commands ###
