"""empty message

Revision ID: 1bde1035444e
Revises: 94fd74155745
Create Date: 2017-08-07 13:59:54.750319

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1bde1035444e'
down_revision = '94fd74155745'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('pull_request_instance_recipe_id_fkey', 'pull_request_instance', type_='foreignkey')
    op.create_foreign_key(None, 'pull_request_instance', 'recipe', ['recipe_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'pull_request_instance', type_='foreignkey')
    op.create_foreign_key('pull_request_instance_recipe_id_fkey', 'pull_request_instance', 'recipe', ['recipe_id'], ['id'])
    # ### end Alembic commands ###
