"""empty message

Revision ID: 3392f5b8fb3c
Revises: d777f0de316d
Create Date: 2017-08-13 13:26:52.631897

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3392f5b8fb3c'
down_revision = 'd777f0de316d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('recipe_drop_in',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('script', sa.String(), nullable=False),
    sa.Column('name', sa.String(length=155), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('recipe_drop_in')
    # ### end Alembic commands ###
