"""empty message

Revision ID: 9af43862368f
Revises: 7ed44ace4a57
Create Date: 2017-08-14 15:10:39.773173

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9af43862368f'
down_revision = '7ed44ace4a57'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('github_avatar', sa.String(), nullable=True))
    op.add_column('user', sa.Column('github_username', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'github_username')
    op.drop_column('user', 'github_avatar')
    # ### end Alembic commands ###
