"""empty message

Revision ID: dd9002dc3648
Revises: ebf0bb63c5f6
Create Date: 2017-08-10 13:09:00.884813

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dd9002dc3648'
down_revision = 'ebf0bb63c5f6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('pull_request_instance_repository_link_id_fkey', 'pull_request_instance', type_='foreignkey')
    op.create_foreign_key(None, 'pull_request_instance', 'repository_link', ['repository_link_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'pull_request_instance', type_='foreignkey')
    op.create_foreign_key('pull_request_instance_repository_link_id_fkey', 'pull_request_instance', 'repository_link', ['repository_link_id'], ['id'])
    # ### end Alembic commands ###
