"""empty message

Revision ID: ebf0bb63c5f6
Revises: fe47f0c80abc
Create Date: 2017-08-10 12:50:51.723619

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ebf0bb63c5f6'
down_revision = 'fe47f0c80abc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('repository_link', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'repository_link', 'user', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'repository_link', type_='foreignkey')
    op.drop_column('repository_link', 'user_id')
    # ### end Alembic commands ###
