"""empty message

Revision ID: fe47f0c80abc
Revises: 0bf76680e66e
Create Date: 2017-08-10 12:31:07.778675

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fe47f0c80abc'
down_revision = '0bf76680e66e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pull_request_instance', sa.Column('repository_link_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'pull_request_instance', 'repository_link', ['repository_link_id'], ['id'])
    op.drop_column('pull_request_instance', 'github_owner')
    op.drop_column('pull_request_instance', 'github_repository')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pull_request_instance', sa.Column('github_repository', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('pull_request_instance', sa.Column('github_owner', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'pull_request_instance', type_='foreignkey')
    op.drop_column('pull_request_instance', 'repository_link_id')
    # ### end Alembic commands ###
